on:
  schedule:
    - cron: '* */2 * * *'

jobs:
  updater:
    runs-on: ubuntu-latest

    steps:
      - name: Now
        run: date

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: 'master'

      - name: Update
        run: |
          npm ci
          npm run update
          npm run check
