name: schedule-update
on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  updater:
    runs-on: ubuntu-latest

    steps:
      - name: Now
        run: date

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: 'master'
        run: | # fetch all branches
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Update
        run: |
          npm ci
          npm run update
          npm run check
