name: schedule-update
on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  updater:
    runs-on: ubuntu-latest

    steps:
      - name: now
        run: | 
          date
          TZ=Asia/Shanghai date

      - name: checkout
        uses: actions/checkout@master
        with:
          ref: 'master'
          # Need for triggering workflow other
          token: ${{ secrets.PAT }}

      - name: check
        id: check
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          npm ci
          npm run update
          if [ -z "$(git status --porcelain)" ]; then 
            echo "clean"
            echo "::set-output name=update::false"
          else 
            echo "new update"
            echo "::set-output name=update::true"
          fi

      - name: update
        if: steps.check.outputs.update == true
        run: |
          sh ./scripts/update.sh
