name: schedule-update
on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  updater:
    runs-on: ubuntu-latest

    steps:
      - name: now
        run: | 
          date
          TZ=Asia/Shanghai date

      - name: checkout
        uses: actions/checkout@master
        with:
          ref: 'master'
          # Need for triggering workflow other
          token: ${{ secrets.PAT }}

      - name: check
        id: check
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          npm ci
          npm run update
          unset HAS_CHANGES
          if  [ ! -z "$(git status --porcelain)" ]; then HAS_CHANGES=true ; fi
          echo set-output name=HAS_CHANGES::${HAS_CHANGES}
          echo ::set-output name=HAS_CHANGES::${HAS_CHANGES}

      - name: update
        if: steps.check.outputs.HAS_CHANGES
        run: |
          sh ./scripts/update.sh
